version: '2.1'

# Run: docker-compose --project-name=ocean up

services:
  mongodb:
    image: mongo:3.6
    ports:
    - "27017:27017"
    command: mongod
    networks:
    - backend

  parity-node:
    image: parity/parity:stable
    command:
      --config /home/parity/parity/config/validator.toml
      --db-path /home/parity/chains
      --keys-path /home/parity/.local/share/io.parity.ethereum/keys
      --base-path /home/parity/base
      --engine-signer 0x00bd138abd70e2f00903268f3db08f2d25677c9e
      --jsonrpc-interface 0.0.0.0
      --ws-interface 0.0.0.0
      --ui-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
      --unlock 0x00bd138abd70e2f00903268f3db08f2d25677c9e
    # entrypoint: tail -f /dev/null
    volumes:
      - ./parity/parity/config:/home/parity/parity/config
      - parity-node:/home/parity/.local/share/io.parity.ethereum/
      - ./parity/parity/authorities/validator0.json:/home/parity/.local/share/io.parity.ethereum/keys/ocean-network/validator.json
      - ./parity/parity/keys:/home/parity/.local/share/io.parity.ethereum/keys/ocean-network
      - ./parity/parity/authorities/validator0.pwd:/home/parity/parity/validator.pwd
      - ./parity/parity/node0.network.key:/home/parity/.local/share/io.parity.ethereum/network/key
    ports:
      - 8545:8545
    networks:
    - backend

  keeper-contracts:
    image: oceanprotocol/keeper-contracts:${OCEAN_VERSION:-stable}
    networks:
    - backend
    environment:
      LOCAL_CONTRACTS: "true"
      DEPLOY_CONTRACTS: ${DEPLOY_CONTRACTS}
      DATABASE_PATH: "/ganache-db"
      REUSE_DATABASE: ${REUSE_DATABASE}
      NETWORK_NAME: ${KEEPER_NETWORK_NAME}
      POA_HOST: "parity-node"
    volumes:
    - ${ARTIFACTS_FOLDER}:/keeper-contracts/artifacts/
    - ${GANACHE_DATABASE_PATH}/ganache-db:/ganache-db

  aquarius:
    image: oceanprotocol/aquarius:${OCEAN_VERSION:-stable}
    ports:
    - 5000:5000
    networks:
    - backend
    depends_on:
    - keeper-contracts
    environment:
      KEEPER_HOST: http://parity-node
      DB_HOSTNAME: mongodb
      LOCAL_CONTRACTS: 'true'
    volumes:
    - ${ARTIFACTS_FOLDER}:/usr/local/keeper-contracts/:ro


networks:
  backend:

volumes:
  parity-node:
