version: '2.1'
services:
  keeper-node:
    image: parity/parity:stable
    command:
      --chain kovan
      --light
      --ws-interface all
      --jsonrpc-cors all
      --jsonrpc-interface all
      --jsonrpc-hosts all
      --jsonrpc-apis all
      --unsafe-expose
    ports:
      - 8545:8545
    networks:
      backend:
        ipv4_address: 172.15.0.12
