version: '3'
services:
  aquarius:
    image: oceanprotocol/aquarius:${AQUARIUS_VERSION:-stable}
    ports:
    - 5000:5000
    networks:
      backend:
        ipv4_address: 172.15.0.15
    environment:
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PORT: ${DB_PORT}
