version: '2.1'
services:
  brizo:
    image: oceanprotocol/brizo:${OCEAN_VERSION:-stable}
    ports:
    - 8030:8030
    networks:
      backend:
        ipv4_address: 172.15.0.17
    depends_on:
    - keeper-contracts
    env_file:
    - ${BRIZO_ENV_FILE}
    environment:
      KEEPER_URL: http://${RPC_URL}:8545
    volumes:
    - ${ARTIFACTS_FOLDER}:/usr/local/keeper-contracts/:ro
