version: '3'
services:
  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION:-latest}
    ports:
      - 9200:9200
    networks:
      backend:
        ipv4_address: 172.15.0.6
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      MAX_MAP_COUNT: "64000"
      discovery.type: "single-node"
      ELASTIC_PASSWORD: "changeme"
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
