version: '3'
services:
  pleuston:
    image: oceanprotocol/pleuston:$PLEUSTON_VERSION
    networks:
      backend:
        ipv4_address: 172.15.0.19
    ports:
    - 3000:3000
    depends_on:
    - keeper-node
    - aquarius
    - brizo
    environment:
      LOCAL_CONTRACTS: ${KEEPER_DEPLOY_CONTRACTS}
      REACT_APP_AQUARIUS_URI: ${AQUARIUS_URI}
      REACT_APP_BRIZO_ADDRESS: ${PUBLISHER_ADDRESS}
    volumes:
    - ${KEEPER_ARTIFACTS_FOLDER}:/pleuston/node_modules/@oceanprotocol/keeper-contracts/artifacts/:ro
