version: '2.1'
services:
  secret-store:
    image: oceanprotocol/parity-ethereum:master
    entrypoint: /entrypoint.sh
    environment:
      CONFIGURE_ACL: "${CONFIGURE_ACL}"
      ACL_CONTRACT_ADDRESS: "${ACL_CONTRACT_ADDRESS}"
      NETWORK: "${KEEPER_NETWORK_NAME}"
    command:
      --config /etc/parity/secretstore/config.toml
      --jsonrpc-cors all
      --jsonrpc-interface all
      --jsonrpc-hosts all
      --jsonrpc-apis all
      --no-warp
    volumes:
      - ../networks/secret-store/config/:/etc/parity/secretstore/
      - secret-store:/secret-store/
      - ../networks/secret-store/keys/:/parity_data/keys/spree/
      - ${KEEPER_ARTIFACTS_FOLDER}:/contracts
    ports:
      - 12000:12000
      - 12001
    networks:
      backend:
        ipv4_address: 172.15.0.13

  secret-store-cors-proxy:
    image: nginx:alpine
    volumes:
      - ../cors-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - secret-store
    ports:
      - 12001:12001
    networks:
      backend:
        ipv4_address: 172.15.0.16
    command: nginx -g 'daemon off;'

  secret-store-signing-node:
    image: parity/parity:stable
    command:
      --chain /etc/parity/secretstore/chain.json
      --light
      --jsonrpc-interface all
      --jsonrpc-apis secretstore
      --jsonrpc-cors all
      --no-warp
      --keys-path /home/parity/.local/keys
    ports:
      - 9545:8545
    volumes:
      - ../networks/secret-store/keys:/home/parity/.local/keys/spree:ro
      - ../networks/secret-store/config/:/etc/parity/secretstore/
    networks:
      backend:
        ipv4_address: 172.15.0.18
