version: '3'
services:
  secret-store-signing-node:
    image: ${PARITY_IMAGE}
    command:
      --chain dev
      --light
      --ws-interface all
      --jsonrpc-cors all
      --jsonrpc-interface all
      --jsonrpc-hosts all
      --jsonrpc-apis all
      --keys-path /home/parity/.local/keys
      --node-key 0x27881af7f75724e25a9818f6c8e719895c8c9d3512003fc8ad0f47d762a07a79
    ports:
      - 9545:8545
    volumes:
      - ../networks/secret-store/keys:/home/parity/.local/keys
      - ../networks/secret-store/config/:/etc/parity/secretstore/
    networks:
      backend:
        ipv4_address: 172.15.0.18
